# Generated by Django 6.0.6 on 2026-06-22 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='leida',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='leida_en',
        ),
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='website.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_notificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-notificacion__created_at'],
                'unique_together': {('notificacion', 'usuario')},
            },
        ),
    ]
